import { getSession } from '@/auth';
import { Toaster } from '@/components/ui/toaster';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import AuthProvider from './auth-provider';
import './globals.css';
import { Providers } from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getSession();
  return (
    <html
      lang='en'
      suppressHydrationWarning>
      <body>
        <AuthProvider session={session}>
          <Providers>{children}</Providers>
        </AuthProvider>
         <Toaster />
      </body>
    </html>
  );
}